### User Registration API Test
POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
  "name": "Robin Khan 3",
  "email": "robin3@example.com",
  "password": "123456",
  "phone": "01712345777",
  "role": "customer"
}

### User Login API Test
POST https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/auth/signin
Content-Type: application/json

{
  "email": "murad@example.com",
  "password": "123456"
}

### Get All Users API Test
POST https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTXVyYWQgSG9zc2FpbiIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoibXVyYWRAZXhhbXBsZS5jb20iLCJpZCI6MiwiaWF0IjoxNzY1MDc5NDM5LCJleHAiOjE3NjUwOTc0Mzl9.19lcnAmZoZX93GEGDTY7NUNRpNvTbnYR2IuaPQleVIQ

### Update User API Test
PUT http://localhost:5000/api/v1/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXJhZiBIb3NzYWluIiwicm9sZSI6ImN1c3RvbWVyIiwiZW1haWwiOiJhcmFmQGV4YW1wbGUuY29tIiwiaWQiOjMsImlhdCI6MTc2NTA4NDY4OCwiZXhwIjoxNzY1MTAyNjg4fQ.M1e2UxtnlQMkb0lKEbLUzapaFCGHlnb5ERB18xqDwtA

{
  "name": "Araf Hossain",
  "role": "customer"
}

### Delete User API Test
DELETE https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/users/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTXVyYWQgSG9zc2FpbiIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoibXVyYWRAZXhhbXBsZS5jb20iLCJpZCI6MiwiaWF0IjoxNzY1MDc5NDM5LCJleHAiOjE3NjUwOTc0Mzl9.19lcnAmZoZX93GEGDTY7NUNRpNvTbnYR2IuaPQleVIQ

### Vehicle Creation API Test
POST https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTXVyYWQgSG9zc2FpbiIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoibXVyYWRAZXhhbXBsZS5jb20iLCJpZCI6MiwiaWF0IjoxNzY1MDc5NDM5LCJleHAiOjE3NjUwOTc0Mzl9.19lcnAmZoZX93GEGDTY7NUNRpNvTbnYR2IuaPQleVIQ

{
  "vehicle_name": "Toyota Camry 2024 for delete",
  "type": "car",
  "registration_number": "ABC-1210",
  "daily_rent_price": 50,
  "availability_status": "available"
}

### Get All Vehicles API Test
GET https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/vehicles

### Get Vehicle By ID API Test
GET https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/vehicles/1

### Update Vehicle API Test
PUT https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/vehicles/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTXVyYWQgSG9zc2FpbiIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoibXVyYWRAZXhhbXBsZS5jb20iLCJpZCI6MiwiaWF0IjoxNzY1MDc5NDM5LCJleHAiOjE3NjUwOTc0Mzl9.19lcnAmZoZX93GEGDTY7NUNRpNvTbnYR2IuaPQleVIQ

{
  "vehicle_name": "Toyota Camry 2024 DDD",
  "type": "car",
  "registration_number": "ABC-2222",
  "daily_rent_price": 55,
  "availability_status": "available"
}

### Delete Vehicle API Test
DELETE https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/vehicles/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTXVyYWQgSG9zc2FpbiIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoibXVyYWRAZXhhbXBsZS5jb20iLCJpZCI6MiwiaWF0IjoxNzY1MDc5NDM5LCJleHAiOjE3NjUwOTc0Mzl9.19lcnAmZoZX93GEGDTY7NUNRpNvTbnYR2IuaPQleVIQ

### Create Booking API Test http://localhost:5000
POST https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTXVyYWQgSG9zc2FpbiIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoibXVyYWRAZXhhbXBsZS5jb20iLCJpZCI6MiwiaWF0IjoxNzY1MDc5NDM5LCJleHAiOjE3NjUwOTc0Mzl9.19lcnAmZoZX93GEGDTY7NUNRpNvTbnYR2IuaPQleVIQ

{
  "customer_id": 4,
  "vehicle_id": 2,
  "rent_start_date": "2025-12-23",
  "rent_end_date": "2025-12-24"
}

### Get All Booking API Test
GET https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTXVyYWQgSG9zc2FpbiIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoibXVyYWRAZXhhbXBsZS5jb20iLCJpZCI6MiwiaWF0IjoxNzY1MDc5NDM5LCJleHAiOjE3NjUwOTc0Mzl9.19lcnAmZoZX93GEGDTY7NUNRpNvTbnYR2IuaPQleVIQ

### Update Booking API Test
PUT https://assign-2-l2-b6-vehicle-rental-syste.vercel.app/api/v1/bookings/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTXVyYWQgSG9zc2FpbiIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoibXVyYWRAZXhhbXBsZS5jb20iLCJpZCI6MiwiaWF0IjoxNzY1MDc5NDM5LCJleHAiOjE3NjUwOTc0Mzl9.19lcnAmZoZX93GEGDTY7NUNRpNvTbnYR2IuaPQleVIQ

{
  "status": "returned"
}
